### ISSUE TITLE
No plane or plane parts

### ISSUE THREAD

**Issue by laser-laser** [FloatingOriginStudios/BalsaIssues#2] opened 2018-10-21 11:12 UTC
**Describe the bug**

Solo flight, choose map, choose plane ( neither pictures or descriptions of planes are shown ) - loading - standing on map beside a hangar and chessna etc.. theres some fuselage parts on the ground for a brief moment but they disappear. Cant get any plane to spawn. Going Fpv shows a cockpit for less than a second, then returns me to were i was before.

**To Reproduce**
Solo flight, choose map, choose plane

**Expected behavior**
Well its a flight-sim, so having a plane to fly with would be appropriate

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7 x64]
Win 10, Nvidia 960gtx 

**VR (please complete the following information):**
 - Device: Oculus + touch
 - OS: Windows 10

**Additional context**

**Comment by laser-laser** [comment] 2018-10-21 22:50
redownloading and installing on a differnt drive didnt help. No antivirus exept windows 10 onboard security - no notification / log on it blocking anything.
The games folder takes 1,54 gb off hard disk space

**Comment by PsykomantaBrain** [comment] 2018-10-22 15:57
We are investigating this issue, but so far, we haven't been able to reproduce the problem. (It is very likely this is a local issue, otherwise all players would be having this problem). As you can imagine, this makes pinning down the source quite difficult, but we are actively working on it.

The fact that you can't read the manual either suggests that the problem is indeed with reading the config files that are used to set up the game content. 

One thing that could be worth trying is to attempt running the game with administrator privileges. I highly suspect there is some sort of file access problem here. 

Thanks for the additional information.

Cheers

**Comment by laser-laser** [comment] 2018-10-22 19:28
running as admin also doesnt fix it

**Comment by PsykomantaBrain** [comment] 2018-10-22 20:20
Another user posted a possible source of this issue. If your computer is set up to a language other than English, it is possible that it is using regional settings that have different characters for number formatting (commas instead of periods for decimal points and such). That could very well be causing the game to fail parsing data from the cfg files.

If you have your PC set to a language other than English, I would suggest changing the keyboard language in the control panel to English (you can set it as a secondary language), and trying again. Basically, make sure the computer's convention for number formatting is using the same characters as English.

Also refer to [this post](https://www.reddit.com/r/BalsaModelSim/comments/9q2n51/how_to_get_support/e896xzf/) for more information from the user that found it.

Again, thank you for the additional information and your patience. I hope this helps.

Cheers

**Comment by PsykomantaBrain** [comment] 2018-10-22 20:30
Just to follow up, I've tested this here by setting my language format to French, and observed the same symptoms that were reported. It is all too likely this is the cause of the problem then.

To get around this then, go to Control Panel -> Region and Language, and in the Format dropdown, choose English. Then restart the game.

We will roll out a fix for this in the next update, so you won't need to change the language anymore, but for the time being, the workaround above should help.

Cheers

**Comment by PsykomantaBrain** [comment] 2018-10-22 22:28
> hello i have the same issue sry for my bad english i am french^^ this fix " Control Panel -> Region and Language, and in the Format dropdown, choose English. Then restart the game." it is for the oculus sotware? because the issue are always here.
> 
> regards
> 
> damien

Sorry, I'm not sure I understand the question. Changing the region format to English should fix the game failing to load parts (and the manual pages). Just make sure you hit Apply on the control panel window then restart the game for settings to take effect.

Hope this helps,

Cheers

**Comment by daminoudu32** [comment] 2018-10-22 22:46
it works thanks :-) I had changed the language in the oculus software and not on windows 10

**Comment by laser-laser** [comment] 2018-10-23 00:00
switching the region/format worked for me - back on win xp one could use applocale to start a program with different region settings but idk if theres such a thing for windows 10

**Comment by PsykomantaBrain** [comment] 2018-10-23 00:05
Awesome! That's great news!

Not sure if there's a way to do that on Win 10 either, but if the workaround works, I think we can close this issue for the time being. I've set up a Support page on our FAQ with this solution for anyone else having this problem.

The next release will have a proper fix as well (already implemented and tested here), which should remove the need to change any region settings.

Thanks for following up! 

Cheers

**Closed by PsykomantaBrain** 2018-10-23 00:05 UTC
